{{- if or (and (ne .Values.registry.database.type "sqlite") (not .Values.registry.database.existingSecret)) (and .Values.registry.security.auth.enabled (not .Values.registry.security.auth.existingSecret)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-mesh-registry.fullname" . }}-secret
  labels:
    {{- include "mcp-mesh-registry.labels" . | nindent 4 }}
    {{- with .Values.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and (ne .Values.registry.database.type "sqlite") (not .Values.registry.database.existingSecret) }}
  database-username: {{ .Values.registry.database.username | b64enc | quote }}
  database-password: {{ .Values.registry.database.password | b64enc | quote }}
  {{- if eq .Values.registry.database.type "postgres" }}
  database-url: {{ printf "postgres://%s:%s@%s:%d/%s?sslmode=disable" .Values.registry.database.username .Values.registry.database.password .Values.registry.database.host (.Values.registry.database.port | int) .Values.registry.database.name | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and .Values.registry.security.auth.enabled (eq .Values.registry.security.auth.type "token") (not .Values.registry.security.auth.existingSecret) }}
  auth-tokens: {{ .Values.registry.security.auth.tokens | toJson | b64enc | quote }}
  {{- end }}
{{- end }}
